name: Authorize Commit Signing

on:
  pull_request:
    branches: [main]

jobs:
  auth-commit-sig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          # Critical: check out the head commit on the branch. By default,
          # actions/checkout will check out a merge commit built for the pull
          # request and signed by Github itself. Using the pull-request HEAD
          # allows the action to check the latest commit on the pull request,
          # which must be signed by an authorized user before it can be merged.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Authorize with Beyond Identity
        uses: ./ # Uses the action in the root directory
        env:
          # Override the default production URL to point to our rolling
          # environment:
          API_BASE_URL: "https://api.rolling.byndid.run/key-mgmt"
          # TODO: remove this to switch to production, once the API is released.
        with:
          api_token: ${{ secrets.BYNDID_KEY_MGMT_API_TOKEN }}
