name: Push pre-built action

on: [pull_request]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/byndid/auth-commit-sig:${{ github.sha }}

      - name: Output image tag
        run: echo "Pushed tagged image ghcr.io/byndid/auth-commit-sig:${{ github.sha }}"
